### ISSUE TITLE
Latest SDK

### ISSUE THREAD

**Issue by Slavezax** [floatinghotpot/cordova-plugin-facebookads#55]
Hello! I'm trying to implement native ads from this plugin but it gives this error;

Error, FBAdErrorDetailKey={
    code = 33000;
    message = "New bundles must use latest available Audience Network SDK.";
    type = OAuthException;
    url = "https://graph.facebook.com/network_ads_common/";
}}
2017-05-07 21:31:48.195948 Bilemezsin[2201:969821] FacebookAds, onAdFailLoad, {'adNetwork':'FacebookAds','adType':'native','adEvent':'onAdFailLoad','error':2000,'reason':'Server Error'}
2017-05-07 21:31:48.197060 Bilemezsin[2201:969821] error: 2000, reason: Server Error

As I see,  it uses cordova-facebook-audnet-sdk 4.7.0 "Facebook AudienceNetwork SDK for Cordova", I searched the internet but couldn't find the "latest SDK". Facebook says Audience Network SDK is part of Facebook SDK right now.

What can I do?

**Comment by jonas-m-** [comment]
Did you try pull request https://github.com/floatinghotpot/cordova-plugin-facebookads/pull/53?

**Comment by truman303** [comment]
Same issue here. Tried updating to latest audience network sdk but 4.7.0 is the latest??

Any news?

Using ionic 2 framework.

**Comment by Slavezax** [comment]
I think it doesn't compatible with the latest Android SDK right now. The problem is, Google only lets it work with latest SDK. So right now we need somebody with skills to modify the plugin to latest AudienceNetwork.jar. :(

**Comment by floatinghotpot** [comment]
I am trying to upgrade the Facebook audience network SDK to latest (v4.22.1), just follow the Facebook Docs to extract the AudienceNetowrk.framework and AudienceNetowrk.jar and replace the ones in dependency:
https://github.com/floatinghotpot/cordova-facebook-audnet-sdk

It build pass with iOS SDK without any problem, but still under testing for Android SDK, due to a very very slow downloading of gradle. 

BTW, I think the modification from @jonas-m- is very reasonable and should work, but I still cannot verify it myself due to very slow download of gradle and cocoapods. (Once verified okay, I will merge the PR). 

You guys can verify it like this:
$ [sudo] npm install -g plugin-verify
$ plugin-verify https://github.com/jonas-m-/cordova-plugin-facebookads

If it works, you can use it like this:
$ cordova plugin add https://github.com/jonas-m-/cordova-plugin-facebookads

**Comment by Slavezax** [comment]
Hello! Thanks for your reply,

as you said, iOS works but Android is not working even with Jonas' fork.

**Comment by jonas-m-** [comment]
@Slavezax What's wrong? Because I'm using my fork in production right now & it works on both - Android & iOS for me

**Comment by Slavezax** [comment]
Are you using with the latest available AudienceNetwork.jar?

When I try it keeps giving error: 

compileArmv7DebugJavaWithJavac
/Users/B42/Bilemezsin/platforms/android/src/com/rjfun/cordova/facebookads/FacebookAdPlugin.java:211: error: <anonymous com.rjfun.cordova.facebookads.FacebookAdPlugin$1$2> is not abstract and does not override abstract method onLoggingImpression(Ad) in AdListener

    	unit.ad.setAdListener(new AdListener(){
    	                                      ^
/Users/B42/Bilemezsin/platforms/android/src/com/rjfun/cordova/facebookads/FacebookAdPlugin.java:383: error: <anonymous com.rjfun.cordova.facebookads.FacebookAdPlugin$4> is not abstract and does not override abstract method onLoggingImpression(Ad) in AdListener

ad.setAdListener(new AdListener(){

                                 ^
/Users/B42/Bilemezsin/platforms/android/src/com/rjfun/cordova/facebookads/FacebookAdPlugin.java:459: error: <anonymous com.rjfun.cordova.facebookads.FacebookAdPlugin$5> is not abstract and does not override abstract method onLoggingImpression(Ad) in AdListener

ad.setAdListener(new InterstitialAdListener(){

**Comment by Slavezax** [comment]
With different (older) AudienceNetwork.jars it build but says I need the latest SDK to serve ads or keep crashing at pages with ad.

**Comment by jonas-m-** [comment]
@Slavezax Did you try to use my pull request (https://github.com/floatinghotpot/cordova-plugin-facebookads/pull/53) as explained by @floatinghotpot in the previous comment (`cordova plugin add https://github.com/jonas-m-/cordova-plugin-facebookads`)?

Because my fork doesn't use `AudienceNetwork.jar` anymore

**Comment by Slavezax** [comment]
I will try again tonight and will report you the result. Thank you.

**Comment by SidMehta** [comment]
@Slavezax  Were you able to build with the latest sdk?

**Comment by floatinghotpot** [comment]
Hi guys, after troubleshooting, I just found the root cause: a new virtual function is added to AdListener in the new SDK, so it will cause error.
```java
    @Override
    public void onLoggingImpression(Ad ad) {
      // Ad impression logged callback
    }
```

Now it's fixed and published to npm as: 
`cordova-facebook-audnet-sdk@4.22.1`
`cordova-plugin-facebookads@4.22.1`

**Comment by SidMehta** [comment]
Thanks for the update @floatinghotpot  . I just tested out the latest update and found an issue. The application is always crashing with this stack trace : 
```
05-17 21:07:47.594 4310-4310/? D/AndroidRuntime: Shutting down VM
05-17 21:07:47.596 4310-4310/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: vern.gk.hindi, PID: 4310
                                                 java.lang.NoClassDefFoundError: Failed resolution of: Lcom/facebook/ads/internal/view/hscroll/b;
                                                     at com.facebook.ads.NativeAd.a(Unknown Source)
                                                     at com.facebook.ads.NativeAd.registerViewForInteraction(Unknown Source)
                                                     at com.rjfun.cordova.facebookads.FacebookAdPlugin.fireNativeAdLoadEvent(FacebookAdPlugin.java:293)
                                                     at com.rjfun.cordova.facebookads.FacebookAdPlugin$1$2.onAdLoaded(FacebookAdPlugin.java:219)
                                                     at com.facebook.ads.NativeAd$1$1.a(Unknown Source)
                                                     at com.facebook.ads.internal.c.b$1$1.run(Unknown Source)
                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                     at android.os.Looper.loop(Looper.java:135)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
                                                  Caused by: java.lang.ClassNotFoundException: Didn't find class "com.facebook.ads.internal.view.hscroll.b" on path: DexPathList[[zip file "/data/app/vern.gk.hindi-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
                                                     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                     at com.facebook.ads.NativeAd.a(Unknown Source) 
                                                     at com.facebook.ads.NativeAd.registerViewForInteraction(Unknown Source) 
                                                     at com.rjfun.cordova.facebookads.FacebookAdPlugin.fireNativeAdLoadEvent(FacebookAdPlugin.java:293) 
                                                     at com.rjfun.cordova.facebookads.FacebookAdPlugin$1$2.onAdLoaded(FacebookAdPlugin.java:219) 
                                                     at com.facebook.ads.NativeAd$1$1.a(Unknown Source) 
                                                     at com.facebook.ads.internal.c.b$1$1.run(Unknown Source) 
                                                     at android.os.Handler.handleCallback(Handler.java:739) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                     at android.os.Looper.loop(Looper.java:135) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5254) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at java.lang.reflect.Method.invoke(Method.java:372) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
                                                    Suppressed: java.lang.NoClassDefFoundError: com.facebook.ads.internal.view.hscroll.b
                                                     at dalvik.system.DexFile.defineClassNative(Native Method)
                                                     at dalvik.system.DexFile.defineClass(DexFile.java:226)
                                                     at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:219)
                                                     at dalvik.system.DexPathList.findClass(DexPathList.java:321)
                                                     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
                                                            ... 16 more
                                                    Suppressed: java.lang.ClassNotFoundException: com.facebook.ads.internal.view.hscroll.b
                                                     at java.lang.Class.classForName(Native Method)
                                                     at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                     at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                            ... 15 more
                                                  Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
05-17 21:07:47.602 564-747/? W/ActivityManager:   Force finishing activity 1 vern.gk.hindi/.G_KinHindi2017_UPSC_RRB
```

If you want, I can open a separate issue for this. If not a major issue, we can update here only.

Again, thanks a lot for your efforts Raymond :)

**Comment by floatinghotpot** [comment]
Thanks for the quick feedback. I find the issue is in native ad API changes.

In old version of SDK, 
`unit.ad.registerViewForInteraction(unit.tracking);`

In new version of SDK, it requires more arguments.
`nativeAd.registerViewForInteraction(nativeAdContainer,clickableViews);`

This change seems to only impact the native Ad, and no impact on banner and interstitial Ad.

I will trill down, if fixed, will let you know.

**Comment by floatinghotpot** [comment]
BTW, @SidMehta, did you remove the old version `cordova-facebook-audnet-sdk` manually before try the new version?

**Comment by Slavezax** [comment]
Thanks @floatinghotpot. You made me happy and sad at the same time. :)

It builds with no problem. But I was waiting this fix only for native ads. :| Is there any ETA for the fix?

**Comment by floatinghotpot** [comment]
Hi guys, I've fixed the native crash issue, and tested working fine on my android device.

Now it's published to npm as:
`cordova-facebook-audnet-sdk@4.22.2`
`cordova-plugin-facebookads@4.22.2`

Please make sure to remove both from cordova project before re-add new version.

Note: in `cordova-facebook-audnet-sdk@4.22.2`,
* For Android, the Facebook AudNet SDK from maven repo is used, gradle will auto download the latest version (now is v4.22.1) when build project.
* But, for iOS, the SDK in pod repo is not the latest v4.22.1, so I manually download the iOS SDK from Facebook official website, extract FBAudienceNetwork.framework and put into `cordova-facebook-audnet-sdk@4.22.2`.

BTW, we can check the pod version like this:
```bash
$ pod search FBAudienceNetwork

-> FBAudienceNetwork (4.20.0)
   Facebook Audience Network Mobile App Ad SDK
   pod 'FBAudienceNetwork', '~> 4.20.0'
   - Homepage: https://developers.facebook.com/docs/audience-network
   - Source:   https://github.com/facebook/facebook-ios-sdk/releases/download/sdk-version-4.20.0/FBAudienceNetwork-4.20.0.zip
   - Versions: 4.20.0, 4.19.0, 4.18.0, 4.17.0, 4.16.1, 4.16.0, 4.15.1, 4.15.0, 4.14.0, 4.13.1, 4.13.0, 4.12.0, 4.11.0, 4.10.1, 4.10.0, 4.9.1, 4.9.0, 4.7.0, 4.6.0, 4.6.0-beta1,
   4.5.0, 4.1.0, 4.0.1, 4.0.0, 3.23.2, 3.23.1 [master repo]
```

**Comment by SidMehta** [comment]
Thanks @floatinghotpot . The app now builds correctly and native test ads are visible. :)

**Comment by SidMehta** [comment]
I have a query. This most likely is an issue on the audience network side. I am seeing error 1001 : "No Fill" all the time with live ads. Test ads work fine. I have taken care of all the possible cases listed here : https://developers.facebook.com/docs/audience-network/testing 
Is anyone else facing the same issue? I used to see the live ads just fine with previous sdk versions.

**Comment by halkoy** [comment]
I try to build Android with intel xdk latest version but it gives dependency errors. intel xdk can not find the dependencies. I added them manual but I can not find how to link them to main plugin.

**Comment by floatinghotpot** [comment]
@halkoy we need more details, could you please show me the build log?

**Comment by halkoy** [comment]
the build log of intel xdk. I think it can not find the dependencies

Error: Unable to build; intelxdk.config.additions.xml file includes plugin tags, which are no longer 
supported. Use the Intel XDK plugin manager to resolve this issue. See https://software.intel.com/en-us/xdk/docs/add-manage-project-plugins#additions-plugin-tags
Error: Could not retrieve plugin dependencies for FacebookAds'.
Error: Plugin FacebookAds failed to install.
