### ISSUE TITLE
phonegap build error

### ISSUE THREAD

**Issue by pearlwebsolution** [floatinghotpot/cordova-plugin-facebookads#68]
while building app through adobe phonegap so error. Error details below

Build Date: 2017-07-29 05:55:21 +0000
Subproject Path: CordovaLib
Configuration on demand is an incubating feature.
Incremental java compilation is an incubating feature.
:preBuild UP-TO-DATE
:preReleaseBuild UP-TO-DATE
:checkReleaseManifest
:preDebugBuild UP-TO-DATE
:CordovaLib:preBuild UP-TO-DATE
:CordovaLib:preDebugBuild UP-TO-DATE
:CordovaLib:checkDebugManifest
:CordovaLib:prepareDebugDependencies
:CordovaLib:compileDebugAidl
:CordovaLib:compileDebugNdk UP-TO-DATE
:CordovaLib:compileLint
:CordovaLib:copyDebugLint UP-TO-DATE
:CordovaLib:mergeDebugShaders
:CordovaLib:compileDebugShaders
:CordovaLib:generateDebugAssets
:CordovaLib:mergeDebugAssets
:CordovaLib:mergeDebugProguardFiles
:CordovaLib:packageDebugRenderscript UP-TO-DATE
:CordovaLib:compileDebugRenderscript
:CordovaLib:generateDebugResValues
:CordovaLib:generateDebugResources
:CordovaLib:packageDebugResources
:CordovaLib:processDebugManifest
:CordovaLib:generateDebugBuildConfig
:CordovaLib:processDebugResources
:CordovaLib:generateDebugSources
:CordovaLib:incrementalDebugJavaCompilationSafeguard
:CordovaLib:compileDebugJavaWithJavac
:CordovaLib:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
:CordovaLib:processDebugJavaRes UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForDebug
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForDebug
:CordovaLib:mergeDebugJniLibFolders
:CordovaLib:transformNative_libsWithMergeJniLibsForDebug
:CordovaLib:transformNative_libsWithSyncJniLibsForDebug
:CordovaLib:bundleDebug
:CordovaLib:preReleaseBuild UP-TO-DATE
:CordovaLib:checkReleaseManifest
:CordovaLib:prepareReleaseDependencies
:CordovaLib:compileReleaseAidl
:CordovaLib:compileReleaseNdk UP-TO-DATE
:CordovaLib:copyReleaseLint UP-TO-DATE
:CordovaLib:mergeReleaseShaders
:CordovaLib:compileReleaseShaders
:CordovaLib:generateReleaseAssets
:CordovaLib:mergeReleaseAssets
:CordovaLib:mergeReleaseProguardFiles
:CordovaLib:packageReleaseRenderscript UP-TO-DATE
:CordovaLib:compileReleaseRenderscript
:CordovaLib:generateReleaseResValues
:CordovaLib:generateReleaseResources
:CordovaLib:packageReleaseResources
:CordovaLib:processReleaseManifest
:CordovaLib:generateReleaseBuildConfig
:CordovaLib:processReleaseResources
:CordovaLib:generateReleaseSources
:CordovaLib:incrementalReleaseJavaCompilationSafeguard
:CordovaLib:compileReleaseJavaWithJavac
:CordovaLib:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
:CordovaLib:processReleaseJavaRes UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForRelease
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForRelease
:CordovaLib:mergeReleaseJniLibFolders
:CordovaLib:transformNative_libsWithMergeJniLibsForRelease
:CordovaLib:transformNative_libsWithSyncJniLibsForRelease
:CordovaLib:bundleRelease
:prepareComAndroidSupportAnimatedVectorDrawable2531Library
:prepareComAndroidSupportAppcompatV72531Library
:prepareComAndroidSupportCustomtabs2400Library
:prepareComAndroidSupportRecyclerviewV72531Library
:prepareComAndroidSupportSupportCompat2600Alpha1Library
:prepareComAndroidSupportSupportCoreUi2600Alpha1Library
:prepareComAndroidSupportSupportCoreUtils2600Alpha1Library
:prepareComAndroidSupportSupportFragment2600Alpha1Library
:prepareComAndroidSupportSupportMediaCompat2600Alpha1Library
:prepareComAndroidSupportSupportV42600Alpha1Library
:prepareComAndroidSupportSupportVectorDrawable2531Library
:prepareComFacebookAndroidAudienceNetworkSdk4250Library
:prepareComGoogleAndroidExoplayerExoplayerR203Library
:prepareComGoogleAndroidGmsPlayServicesAds1102Library
:prepareComGoogleAndroidGmsPlayServicesAdsLite1102Library
:prepareComGoogleAndroidGmsPlayServicesBase1102Library
:prepareComGoogleAndroidGmsPlayServicesBasement1102Library
:prepareComGoogleAndroidGmsPlayServicesClearcut1102Library
:prepareComGoogleAndroidGmsPlayServicesGass1102Library
:prepareComGoogleAndroidGmsPlayServicesGcm1102Library
:prepareComGoogleAndroidGmsPlayServicesIid1102Library
:prepareComGoogleAndroidGmsPlayServicesLocation1102Library
:prepareComGoogleAndroidGmsPlayServicesSafetynet1102Library
:prepareComGoogleAndroidGmsPlayServicesTasks1102Library
:prepareComOnesignalOneSignal357Library
:prepareProjectCordovaLibUnspecifiedReleaseLibrary
:prepareReleaseDependencies
:compileReleaseAidl
:compileReleaseRenderscript
:generateReleaseBuildConfig
:generateReleaseResValues
:generateReleaseResources
:mergeReleaseResources
:processReleaseManifest/project/AndroidManifest.xml:27:9-38 Error:
	Attribute meta-data#android.support.VERSION@value value=(26.0.0-alpha1) from [com.android.support:support-v4:26.0.0-alpha1] AndroidManifest.xml:27:9-38
	is also present at [com.android.support:appcompat-v7:25.3.1] AndroidManifest.xml:27:9-31 value=(25.3.1).
	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:25:5-27:41 to override.

See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.

:processReleaseManifest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processReleaseManifest'.
> Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(26.0.0-alpha1) from [com.android.support:support-v4:26.0.0-alpha1] AndroidManifest.xml:27:9-38
  	is also present at [com.android.support:appcompat-v7:25.3.1] AndroidManifest.xml:27:9-31 value=(25.3.1).
  	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:25:5-27:41 to override.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4.465 secs
Error: /project/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/project/AndroidManifest.xml:27:9-38 Error:
	Attribute meta-data#android.support.VERSION@value value=(26.0.0-alpha1) from [com.android.support:support-v4:26.0.0-alpha1] AndroidManifest.xml:27:9-38
	is also present at [com.android.support:appcompat-v7:25.3.1] AndroidManifest.xml:27:9-31 value=(25.3.1).
	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:25:5-27:41 to override.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processReleaseManifest'.
> Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(26.0.0-alpha1) from [com.android.support:support-v4:26.0.0-alpha1] AndroidManifest.xml:27:9-38
  	is also present at [com.android.support:appcompat-v7:25.3.1] AndroidManifest.xml:27:9-31 value=(25.3.1).
  	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:25:5-27:41 to override.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
    at ChildProcess.whenDone (/project/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

**Comment by blukis** [comment]
I'm having the same problem.  It seems this is caused by a recent change in PhoneGap build, because the same config.xml built fine for me a few days ago.  Maybe this can be fixed in the plugin tho?

My build log, and a simple failing .zip attached.
[build-log.txt](https://github.com/floatinghotpot/cordova-plugin-facebookads/files/1194005/build-log.txt)
[www.zip](https://github.com/floatinghotpot/cordova-plugin-facebookads/files/1194007/www.zip)

**Comment by ekubischta** [comment]
We are getting the same error

mergeReleaseResources
:processReleaseManifest/project/AndroidManifest.xml:27:9-38 Error:
	Attribute meta-data#android.support.VERSION@value value=(26.0.0-alpha1) from [com.android.support:support-v4:26.0.0-alpha1] AndroidManifest.xml:27:9-38
	is also present at [com.android.support:appcompat-v7:25.3.1] AndroidManifest.xml:27:9-31 value=(25.3.1).
	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:25:5-27:41 to override.


See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.

:processReleaseManifest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processReleaseManifest'.
> Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(26.0.0-alpha1) from [com.android.support:support-v4:26.0.0-alpha1] AndroidManifest.xml:27:9-38
  	is also present at [com.android.support:appcompat-v7:25.3.1] AndroidManifest.xml:27:9-31 value=(25.3.1).
  	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:25:5-27:41 to override.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by W1ldW1ngs** [comment]
@floatinghotpot any insight on what could be causing this?

**Comment by pearlwebsolution** [comment]
@floatinghotpot any insight on what could be causing this? 

hello sir,
       from this month 2nd onwards Adobe Phonegap changes its version and building method. After that, this build error problem starts. Please try to resolve it.

**Comment by W1ldW1ngs** [comment]
@pearlwebsolution 

We are still trying a way to get this plugin working, but only keep running into roadblocks. Hopefully @floatinghotpot answers soon.

**Comment by W1ldW1ngs** [comment]
Any updates on this? We haven't tried it since.

**Comment by pearlwebsolution** [comment]
sir @floatinghotpot  , are you are still maintaining this plugin? Many of we waiting for your reply...

**Comment by W1ldW1ngs** [comment]
This is by far the best plugin if we can get it to work inside of our app in order to deliver backfill inside of our feed scroller app.

At this point this was the only facebook audience network plugin I could find, hopefully it gets patched soon.

**Comment by W1ldW1ngs** [comment]
HUGE news @pearlwebsolution and @blukis we were able to finally get this plugin to build after also picking up this plugin.

https://www.npmjs.com/package/cordova-android-support-gradle-release

Hope it helps anyone running into this problem! :)

**Comment by pearlwebsolution** [comment]
hi friends, As @W1ldW1ngs idea, i used https://www.npmjs.com/package/cordova-android-support-gradle-release , its work for me. working fine. Thanks @W1ldW1ngs .

We are highly thankful to Mr. @floatinghotpot for created this plugin. 

But i highly disappointed for till now no response from Mr. @floatinghotpot . 

Will he maintain this plugin? This question ariased on me due to not answering for this issue.

**Comment by W1ldW1ngs** [comment]
That I'm not sure I but I am hopeful that this plugin will be maintained as this is the only plugin we have found that allows us to run native ads in our app.

**Comment by floatinghotpot** [comment]
The plugin itself is under maintain, but I found it's a quite common issue for project dependent on android support library. 

To avoid using another plugin to fix it, I just create a patch version to fix the issue.
+ cordova-plugin-facebookads@4.23.2

Just like `cordova-android-support-gradle-release` does, insert a gradle file into the project with following content:
```
configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        def requested = details.requested
        if (requested.group == 'com.android.support') {
            if (!requested.name.startsWith("multidex")) {
                details.useVersion '25.+'
            }
        }
    }
}
```
